--select * from tradeloadstaging.dbo.trade_gui order by 1 desc
--select top 100 * from TradeLoadstaging.dbo.GemsAckNACK order by 1 desc
use [TradeLoadstaging]
DECLARE @counter INT = 1;
	--begin tran
    WHILE @counter <= 2
    BEGIN
INSERT INTO tradeloadstaging.dbo.trade_gui
select		[system]
           ,[Processtype]
           ,[BREntiyCode]
           ,[BRPartyIDAccount]
           ,[ReceiveMessageKeyID]
           ,[Account]
           ,[Commission]
           ,[Commission Type]
           ,[Currency]
           ,[Exec ID]
           ,[LastCapacity]
           ,[Last Mkt Or Exchange]
           ,[LastQty]
           ,[SecurityID]
           ,[Side]
           ,[TransactTime]
           ,[FutSettDate]
           ,[Trade Date]
           ,[SettlCurrency]
           ,[ExecType]
           ,[Accrued Interest amount]
           ,[SecurityExchange]
           ,[ContraBroker]
           ,[GrossTradeAmt]
           ,[Price Type]
           ,[Party ID]
           ,[Product]
           ,[MaturityDate]
           ,[9039]
           ,[DaylightNewTime]
           ,[Comment]
           ,[newTradedate]
           ,[CountryCode]
           ,[Path]
           ,[ExchangeRate]
           ,[Status]
           ,[InsertedDateTime]
           ,0--[TradeProcessStatus]
           ,[MSMQID]
           ,[MQSendTime]
           ,[TSSTAg]
           ,[LastUpdatedUser]
           ,getdate() [TradeProcessTimeStamp]
           ,[previous_BrExecID]
           ,[wi]
           ,[Int_Override]
           ,[PostedBy]
           ,[Previous_ID_Rebill]
           ,[Link]
           ,[LastPx]
           ,[source]
           ,[idsource]
           ,[AccountType]
           ,[BlotterCode]
           ,[markup_down]
           ,'EFBVG' + Convert(nvarchar(50),@counter)    [source_BRID]
           ,[Prevailing_Market_Price]
           ,[Non_Institutional_Flag]
           ,[markup_down_percentage]
           ,[PMPStep]
           ,[Rate]
           ,[daycount]
           ,[RetunrDate]
           ,[StartDate]
           ,[Haircut]
           ,[TrailorCode]
           ,[fi_blottercode]  from tradeloadstaging.dbo.trade_gui where SecurityID like '9128%' and TradeID=1520854 --and source_BRID like '%EFBVG%'
      SET @counter = @counter + 1;
    END;
		  select * from tradeloadstaging.dbo.trade_gui where SecurityID like '9128%' order by TradeID desc
	 -- rollback tran